<!DOCTYPE html>
<html>
<head>
	<title>L'Histoire de Pablo Escobar</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f2f2f2;
		}
		
		header {
			background-color: #222;
			color: #fff;
			padding: 20px;
			text-align: center;
			font-size: 32px;
			margin-bottom: 20px;
		}
		
		nav {
			background-color: #555;
			color: #fff;
			padding: 10px;
			text-align: center;
			margin-bottom: 20px;
		}
		
		nav ul {
			list-style: none;
			display: inline-block;
			margin: 0;
			padding: 0;
		}
		
		nav ul li {
			display: inline-block;
			margin: 0 10px;
		}
		
		nav ul li a {
			color: #fff;
			text-decoration: none;
			font-size: 16px;
			padding: 5px 10px;
			border-radius: 5px;
			background-color: #888;
			transition: background-color 0.2s ease-in-out;
		}
		
		nav ul li a:hover {
			background-color: #666;
		}
		
		main {
			display: flex;
			flex-wrap: wrap;
			justify-content: center;
			align-items: center;
		}
		
		section {
			background-color: #fff;
			padding: 20px;
			margin: 20px;
			border-radius: 5px;
			box-shadow: 0px 0px 5px 1px rgba(0,0,0,0.2);
			flex-basis: 500px;
			max-width: 100%;
		}
		
		h2 {
			font-size: 24px;
			margin-top: 0;
			margin-bottom: 10px;
		}
		
		p {
			font-size: 16px;
			margin-top: 0;
		}
		
		img {
			max-width: 100%;
			height: auto;
			margin-bottom: 10px;
		}
		
		@keyframes slide-in {
			from {
				transform: translateY(-100%);
			}
			to {
				transform: translateY(0%);
			}
		}
		
		.slide-in {
			animation: slide-in 1s ease-in-out;
		}
	</style>
</head>
<body>
	<header>
		<h1>L'Histoire de Pablo Escobar</h1>
	</header>
	
	<nav>
		<ul>
			<li><a href="#histoire">Histoire</a></li>
			<li><a href="#photos">Photos</a></li>
			<li><a href="#videos">Vidéos</a></li>
		</ul>
	</nav>
	
	<main>
		<section id="histoire" class="slide-in">
			<h2>L'Ascension de Pablo Escobar</h2>
			<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pablo_Escobar%2C_Mug_shot_198
